version: '3.8'
services:
  spark-master:
    image: bitnami/spark:3.2.4
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - /home/luke/spark-master/library/mysql-connector-j-8.0.33.jar:/opt/bitnami/spark/jars/mysql-connector-j-8.0.33.jar
      - /home/luke/spark-master/library/stopword.txt:/opt/bitnami/spark/stopword.txt
      - /home/luke/spark-master/library/pip-install.sh:/opt/bitnami/spark/pip-install.sh
    environment:
      - SPARK_MODE=master


  spark-worker-1:
    image: bitnami/spark:3.2.4
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    volumes:
      - /home/ubuntu/spark-master/library/mysql-connector-j-8.0.33.jar:/opt/bitnami/spark/jars/mysql-connector-j-8.0.33.jar
      - /home/ubuntu/spark-master/library/stopword.txt:/opt/bitnami/spark/stopword.txt
      - /home/ubuntu/spark-master/library/pip-install.sh:/opt/bitnami/spark/pip-install.sh
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=4G
      - SPARK_WORKER_CORES=2

  spark-worker-2:
    image: bitnami/spark:3.2.4
    container_name: spark-worker-2
    depends_on:
     - spark-master
    ports:
     - "8082:8081"
    volumes:
      - /home/ubuntu/spark-master/library/mysql-connector-j-8.0.33.jar:/opt/bitnami/spark/jars/mysql-connector-j-8.0.33.jar
      - /home/ubuntu/spark-master/library/stopword.txt:/opt/bitnami/spark/stopword.txt
      - /home/ubuntu/spark-master/library/pip-install.sh:/opt/bitnami/spark/pip-install.sh
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=4G
      - SPARK_WORKER_CORES=2


  spark-worker-3:
    image: bitnami/spark:3.2.4
    container_name: spark-worker-3
    depends_on:
      - spark-master
    ports:
      - "8083:8081"
    volumes:
      - /home/ubuntu/spark-master/library/mysql-connector-j-8.0.33.jar:/opt/bitnami/spark/jars/mysql-connector-j-8.0.33.jar
      - /home/ubuntu/spark-master/library/stopword.txt:/opt/bitnami/spark/stopword.txt
      - /home/ubuntu/spark-master/library/pip-install.sh:/opt/bitnami/spark/pip-install.sh
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=4G
      - SPARK_WORKER_CORES=2